# Default values for devguard.
# This is a YAML-formatted file.
# Declare variables to be passed into templates.

########################
## Authentication Related Settings (Kratos)
######
webauthn:
  enabled: false
passkey:
  enabled: true
password:
  enabled: true
totp:
  enabled: false
verificationAfterSignUp:
  enabled: true
oidc:
  enabled: false
  providers: []
  # - id: github
  #   provider: github
  #   clientId: "sample-client-id"
  #   existingClientSecretName: github-client-secret # needs to contain key "secret"
  # - id: gitlab
  #   provider: gitlab
  #   issuerUrl: https://gitlab.de
  #   clientId: client-id
  #   existingClientSecretName: gitlab-secret
  #   existingAdminTokenSecretName: gitlab-admin-token # needs to contain key "token"
  #   scope:
  #     - read_user
  #     - openid
  #     - profile
  #     - email

networkPolicy:
  enabled: true
  #ingressNamespaceSelectorKey: "role"
  #ingressNamespaceSelectorValue: "ingress"
mail:
  # needs to contain key: "uri". Format should be like: smtps://<user>@<your-domain.com>:<secret>@<mail-server.de>:465/?skip_ssl_verify=false
  existingSMTPConnectionUriSecret: ""
  fromAddress: "noreply@devguard.org"
  fromName: "DevGuard"


########################
## DevGuard API Settings
######
api:
  replicaCount: 1
  ciComponentBase: "https://gitlab.com/l3montree/devguard/-/raw/main"
  # needs to contain keys: "passphrase", "privateKey", "publicKey", "fingerprint"
  # the openGpg keys need to be in pem format.
  # Generate keys: gpg --full-generate-key
  # List key ids: gpg --list-secret-keys --keyid-format LONG
  # Export public key: gpg --armor --export "$KEY_ID" > "$OUTPUT_DIR/${KEY_ID}_public.asc"
  # Export private key: gpg --armor --export-secret-keys "$KEY_ID" > "$OUTPUT_DIR/${KEY_ID}_private.asc"
  existingCsafSecretName: ""
  image:
    repository: ghcr.io/l3montree-dev/devguard
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: 0.13.0
  imagePullSecrets: []
  errorTracking:
    # https://<your-error-tracking-dsn>
    dsn: ""
    # can be dev, stage or prod
    environment: "dev"
  intoto:
    existingPrivateKeySecretName: ec-private-key
  # GitHub App Integration Settings
  github:
    enabled: true
    appId: abc
    # needs to contain "webhookSecret"
    existingWebhookSecretSecretName: github-app-webhook-secret
    # needs to contain key "privateKey"
    existingPrivateKeySecretName: github-app-private-key

  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: example.com
        paths:
          - path: /
            pathType: Prefix
  
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80


########################
## DevGuard Web Frontend Settings
######
web:
  replicaCount: 1
  image:
    repository: ghcr.io/l3montree-dev/devguard-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: 0.13.0
  imagePullSecrets: []

  ciComponentBase: "https://gitlab.com/l3montree/devguard/-/raw/main"
  devguardApiUrlPublicInternet: ""
  privacyPolicyLink: ""
  termsOfUseLink: ""
  imprintLink: ""
  accountDeletionMail: ""
  # Custom Theme URLs (leave empty to use default theme)
  themeJsUrl: ""
  themeCssUrl: ""
  errorTracking:
    # https://<your-error-tracking-dsn>
    dsn: ""

  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: app.example.com
        paths:
          - path: /
            pathType: Prefix

  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80


########################
## DevGuard PostgreSQL Database Settings
######
postgresql:
  image:
    # Please note: we are using a custom PostgreSQL image that has the required
    # extensions pre-installed.
    repository: ghcr.io/l3montree-dev/devguard/postgresql
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: v0.17.0
  pvc:
    size: 21Gi
  podAnnotations: {}
